### ISSUE TITLE
Einbindung von Videos aus FAU Videoportal defekt

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-oembed#12]
Siehe: https://www.wordpress.rrze.fau.de/plugins/fau-oembed/

Zunächst kommt gar nichts, dann die Meldung "Setup Timeout Error: Setup took longer than seconds to complete.

Bitte mal nachsehen, eventuell auch beim Multimediateam nachfragen. 

![bildschirmfoto 2017-04-24 um 12 32 26](https://cloud.githubusercontent.com/assets/11296947/25333350/1d716e0c-28ea-11e7-8600-90e31f67bab8.png)

**Comment by xwolfde** [comment]
fixed im update
