### ISSUE TITLE
[faukarte] - individuelle Markersymbole?

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/fau-oembed#15]
Wenn man in der mobilen Ansicht auf einer eingebundenen Karte die Punkte anklickt, zentriert der Kartenausschnitt/Das Kartenfenster nicht richtig auf den Popup / er wird z.T. abgeschnitten und von Steuerelementen verdeckt. Betrifft komischerweise aber nicht alle Popups gleichermaßen (evtl. liegt das auch an einer fehlerhaften Formatierung im GeoJSON, die zu diesen großen weißen Flächen in den Popups führt??)
Vergleiche:
https://karte.fau.de/source/public
https://geographie.cms.rrze.uni-erlangen.de/forschung/wissenschaftliche-kooperationen/

Außerdem wäre es wünschenswert, im geojson eigene Markersymbole vergeben zu können (habe bisher nicht rausgefunden, wie man im geojson einen anderen Marker als den Standard-blauen hinbekommt. Eine Dokumentation des Kartenplugins und der verwendeten Symbolbibliotheken wäre nett).
![faukarte_mobileansicht_popups2](https://user-images.githubusercontent.com/11389126/36945980-0d24b284-1fb6-11e8-9a3d-28cc38cc5147.PNG)
![faukarte_mobileansicht_popups](https://user-images.githubusercontent.com/11389126/36945982-0f011e30-1fb6-11e8-936a-6f8e87a2cb71.PNG)

edit: beim Herumprobieren war mir auch aufgefallen, dass sich im Kartenrahmen ein "Browserfenster" öffnet, wenn Links im GeoJSON nicht mit target="_blank" ausgezeichnet werden. Dies sollte m. E. vom Plugin grundsätzlich verhindert werden.

**Comment by Albager** [comment]
OK - die großen weißen flächen kamen von `<span>`-Elementen im HTML-Content der Popups. Wenn man das Display in der mobilen Ansicht bei großen Popups dreht, ist auch das Verdeckungs-Problem halbwegs handzuhaben.

**Comment by Albager** [comment]
Die Frage nach den individuellen Markersymbolen bleibt natürlich offen...

**Comment by xwolfde** [comment]
Beides müsste bei karte.fau.de gemacht werden: Die Symbole können durch eigene Overlays gemacht werden - dazu muss man sich dort einloggen und dann eben definieren was man will.
Das resposnive Vergalten der Icons im Kartenausschnitt ist auch Sache der Karte. Da bin ich mir aber nicht sicher, ob wir da was machen können.

Bei Fragen zu der Karte bitte über Mail, dann krieg es der richtig - mit dem Theme hat es nichts weiter zu tun.
