### ISSUE TITLE
Embedding BR

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-oembed#21]
Zum einbetten kann man folgende URL verwenden: 
https://www.br.de/mediathek/embed/campus-magazin-30052019-was-kommt-nach-dem-abi-ideen-fuer-die-studienwahl-av:5cb70f68cf372a001a27751b 

Sie selbst geben folgenden Code an: 
`<div style="width:100%;padding-top:56.25%;position:relative;background:#000;"><iframe allowfullscreen style="position:absolute;left:0;right:0;bottom:0;top:0;border:0;height:100%;width:100%;" src="https://www.br.de/mediathek/embed/campus-magazin-30052019-was-kommt-nach-dem-abi-ideen-fuer-die-studienwahl-av:5cb70f68cf372a001a27751b"></iframe></div> `

Es muss also im Prinzip von der eigentlichen URL (nur) "/video/" durch "/embed/" ersetzen.

**Comment by migrosch** [comment]
# #22
