### ISSUE TITLE
Wunsch zur EInbindung von Canva.com

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-oembed#38]
Es gibt den Wunsch, auch Canva einzubinden.

Vgl.-  Ticket 2023080742001771

Doku dazu: https://www.canva.com/help/embed-designs/

Beispiel-URL hier:  https://www.canva.com/design/DAFYzR6h8IA/view.

**Comment by lukasniebler** [comment]
Da Canva vom offiziellen WordPress Projekt derzeit nicht als oEmbed-Provider unterstützt wird, und auch keine offizielle Doku zur oEmbed-Schnittstelle vorliegt wird es vorerst kein Canva-Embedding geben.

Falls Canva irgendwann in die offizielle WP Codebase als oEmbed-Provider aufgenommen wird, kann man das erneut überlegen. 

s. https://developer.wordpress.org/reference/hooks/oembed_providers/
