### ISSUE TITLE
Möglichkeit via Shortcodes Alt- und Titel-Tags einzufügen?

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-oembed#7]
Es wäre gut, wenn man bei Shortcodes zb bei Fau-Karte Alt- und/oder titel-Tags angeben könnte, oder ist das bereits irgendwie integriert, falls die Karte nicht angezeigt werden kann? ZB Wie man auch width= oder height= angeben kann als Parameter.

Wäre auch relevant bei Videos oder Galerien (wobei man den Bildern zwar Alt-Tag aber keinen Titel-Tag geben kann (außer via html-Editor))

Bzw. ist das überhaupt eine berechtigte Frage oder total Nonsense?

Evtl sind das mehrere Issues in einem. Könnten wir mal im Jour-fixe besprechen, falls relevant.

**Comment by xwolfde** [comment]
Bei den Embeds von YT und Video kommt der Titel aus den Daten des Videos, wird aber via Option sichtbar sein oder nur als Schema Org Markup.
Bei Karte macht es kein Sinn und da kommt kein automatischer Titel. Da muss man von Hand einen sinnvollen Titel über der Karte angeben.
