### ISSUE TITLE
Darstellungsfehler in Internet Explorer (11)

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-oembed#9]
Bei gleichzeitiger Einbindung eines Youtube-Videos (nicht getestet mit anderen Videoportalen) und eines Bildlinks mit der css-Klasse "lightbox" kommt es zu einem Darstellungsfehler. Dabei wird die Lightbox von dem Youtube-Player überlagert. Siehe Anhang.

![oembed_lightbox_error1](https://cloud.githubusercontent.com/assets/6545158/13701783/643defd8-e78a-11e5-81f3-311fa7de4f2a.png)

**Comment by xwolfde** [comment]
Ich vermute, da müssen wir mal in dem z-Index des players schauen. Ist zwar toll, dass es HTML5 ist, aber als ich da zuletzt reinschaute war der scary.

**Comment by xwolfde** [comment]
Tritt mit neuer Version nicht mehr auf
